java_library(
    name = "mockito-core",
    srcs = glob(["src/main/java/**/*.java"]),
    visibility = ["//visibility:public"],
    deps = [
        "@maven//:net_bytebuddy_byte_buddy",
        "@maven//:net_bytebuddy_byte_buddy_agent",
        "@maven//:org_objenesis_objenesis",
        "@maven//:junit_junit",
        "@maven//:org_opentest4j_opentest4j",
        "@maven//:org_hamcrest_hamcrest",
    ],
)
